# Generated by Django 3.2.9 on 2021-12-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosBem',
            fields=[
                ('id_estado_bem', models.AutoField(primary_key=True, serialize=False)),
                ('estado_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('id_user_cad', models.IntegerField(default=1)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('id_user_alt', models.IntegerField(default=1)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=80)),
                ('id_user_cad', models.IntegerField(default=1)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('id_user_alt', models.IntegerField(default=1)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NaturezasDespesa',
            fields=[
                ('id_natureza_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('cod_natureza_despesa', models.CharField(max_length=8)),
                ('desc_natureza_despesa', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoUsoBem',
            fields=[
                ('id_situacao_uso_bem', models.AutoField(primary_key=True, serialize=False)),
                ('situacao_uso_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NotasFiscais',
            fields=[
                ('id_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('id_user_cad', models.IntegerField(default=1)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('id_user_alt', models.IntegerField(default=1)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_bens.fornecedores')),
                ('id_natureza_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_bens.naturezasdespesa')),
            ],
        ),
        migrations.CreateModel(
            name='ItensNotaFiscal',
            fields=[
                ('id_item_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_servico', models.CharField(max_length=100)),
                ('vinculado', models.CharField(max_length=1)),
                ('id_user_cad', models.IntegerField(default=1)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('id_user_alt', models.IntegerField(default=1)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_bens.notasfiscais')),
            ],
        ),
        migrations.CreateModel(
            name='Bens',
            fields=[
                ('id_bem', models.AutoField(primary_key=True, serialize=False)),
                ('tombamento', models.CharField(max_length=10)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_lim_garantia', models.DateField()),
                ('data_fim_garantia', models.DateField()),
                ('data_inicio_uso', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_user_cad', models.IntegerField(default=1)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('id_user_alt', models.IntegerField(default=1)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_estado_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_bens.estadosbem')),
                ('id_item_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_bens.itensnotafiscal')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_bens.marca')),
                ('id_situacao_uso_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_bens.situacaousobem')),
            ],
        ),
    ]
